/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Semantic tokens backed by CSS variables ────────────────────────
        // These automatically flip in dark mode when .dark is on <html>
        "background":                  "var(--c-bg)",
        "surface":                     "var(--c-surface)",
        "surface-bright":              "var(--c-surface-bright)",
        "surface-container-lowest":    "var(--c-surface-lowest)",
        "surface-container-low":       "var(--c-surface-low)",
        "surface-container":           "var(--c-surface-container)",
        "surface-container-high":      "var(--c-surface-high)",
        "surface-container-highest":   "var(--c-surface-highest)",
        "surface-dim":                 "var(--c-surface-dim)",
        "surface-variant":             "var(--c-surface-variant)",
        "on-surface":                  "var(--c-on-surface)",
        "on-surface-variant":          "var(--c-on-surface-variant)",
        "on-background":               "var(--c-on-bg)",
        "outline":                     "var(--c-outline)",
        "outline-variant":             "var(--c-outline-variant)",
        "inverse-surface":             "var(--c-inverse-surface)",
        "inverse-on-surface":          "var(--c-inverse-on-surface)",

        // ── Brand / accent (same in both modes, just slightly adapted) ─────
        "primary":                     "var(--c-primary)",
        "on-primary":                  "#ffffff",
        "primary-container":           "var(--c-primary-container)",
        "on-primary-container":        "var(--c-on-primary-container)",
        "primary-fixed":               "var(--c-primary-fixed)",
        "primary-fixed-dim":           "var(--c-primary-fixed-dim)",
        "on-primary-fixed":            "#001c39",
        "on-primary-fixed-variant":    "var(--c-on-primary-fixed-variant)",
        "inverse-primary":             "#a3c9ff",
        "surface-tint":                "var(--c-primary)",

        "secondary":                   "var(--c-secondary)",
        "on-secondary":                "#ffffff",
        "secondary-container":         "var(--c-secondary-container)",
        "secondary-fixed":             "#d4e3ff",
        "secondary-fixed-dim":         "#a4c9ff",
        "on-secondary-fixed":          "#001c39",
        "on-secondary-fixed-variant":  "#074882",
        "on-secondary-container":      "#114c86",

        "tertiary":                    "#355e89",
        "on-tertiary":                 "#ffffff",
        "tertiary-container":          "#4f77a4",
        "on-tertiary-container":       "#fdfcff",
        "tertiary-fixed":              "#d1e4ff",
        "tertiary-fixed-dim":          "#a1cafb",
        "on-tertiary-fixed":           "#001d36",
        "on-tertiary-fixed-variant":   "#1c4973",

        "error":                       "#ba1a1a",
        "on-error":                    "#ffffff",
        "error-container":             "#ffdad6",
        "on-error-container":          "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "full":    "9999px",
        "card":    "24px",
        "button":  "12px",
      },
      spacing: {
        "xs":            "8px",
        "base":          "4px",
        "sm":            "16px",
        "md":            "24px",
        "gutter":        "24px",
        "lg":            "40px",
        "xl":            "64px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans:               ["Inter", "sans-serif"],
        "body-sm":          ["Inter", "sans-serif"],
        "headline-lg":      ["Inter", "sans-serif"],
        "headline-sm":      ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md":      ["Inter", "sans-serif"],
        "body-lg":          ["Inter", "sans-serif"],
        "label-md":         ["Inter", "sans-serif"],
        "display":          ["Inter", "sans-serif"],
        "label-sm":         ["Inter", "sans-serif"],
        "body-md":          ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm":    ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md":   ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm":   ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-md":    ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg":    ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm":["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md":["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg":["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display":    ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
